# -*- Makefile -*-
#
# Makefile.config - Customized configuration for ONScripter
#

#
# Charset for ONScripter
# Switch: SJIS <-> GBK
#
CONFIG_CHARSET = GBK

ifeq ($(CONFIG_CHARSET), GBK)
CFLAGS += -DCHARSET_GBK
else
CFLAGS += -DCHARSET_SJIS
endif
